
project_id = "lopilymjfynocjddhiig"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.llama-search]
verify_jwt = true

[functions.llama-chat]
verify_jwt = true

