
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lopilymjfynocjddhiig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcGlseW1qZnlub2NqZGRoaWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzE3NzUsImV4cCI6MjA1NzQ0Nzc3NX0.NGycpJGD_4FJp-wm-LAdQ7GTQWsQg4XVgrMowgQvNDk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
